http:
  port: 8080

apiEndpoints:
  authApi:
    host: localhost
    paths:
      - /auth/*

  backendApi:
    host: localhost
    paths:
      - /api/*

serviceEndpoints:
  authService:
    url: 'http://localhost:3000'

  backendService:
    url: 'http://localhost:3001'

policies:
  - logRequest
  - jwt
  - proxy
  - rate-limit # https://www.express-gateway.io/docs/policies/rate-limiter/

pipelines:
  authPipeline:
    apiEndpoints:
      - authApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              headers:
                x-gateway-auth: ${GATEWAY_AUTH_TOKEN} # Replace 'my-secret-token-123' with a strong secret string that only your gateway and backend know.

  backendPipeline:
    apiEndpoints:
      - backendApi
    policies:
      - logRequest:
          - action:
              messagePrefix: '[API Request] '
      - rate-limit:
          - action:
              max: 4 # Maximum 4 requests per minute
              windowMs: 60000
              rateLimitBy: "${req.hostname}"
      - jwt:
          - action:
              secretOrPublicKeyFile: ./certs/public.pem
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: backendService
              headers:
                x-gateway-auth: ${GATEWAY_AUTH_TOKEN} # Replace 'my-secret-token-123' with a strong secret string that only your gateway and backend know.
